pipeline {
    agent any
    options {
        skipDefaultCheckout ()
    }
    tools{ 
        nodejs 'node'
    }

    stages{
        stage ('Checkout Frontend'){
            steps {
                dir('devopswiki-fe') {
                    git branch: 'dev', credentialsId:'gh-yawnartey', url:'https://github.com/yawnartey/devopswiki-fe'
                }
            }
        }
        stage ('Checkout Backend') {
            steps {
                dir('devopswiki-be') {
                    git branch: 'dev', credentialsId:'gh-yawnartey', url:'https://github.com/yawnartey/devopswiki-be'
                }
            }
        }
        stage ('Checkout Containerisation') {
            steps {
                dir('devopswiki-containerisation') {
                    git branch: 'dev', credentialsId: 'gh-yawnartey', url: 'https://github.com/yawnartey/devopswiki-containerisation'
                }
            }
        }
        stage ('Build App') {
            parallel {
                stage('FastAPI Backend Build') {
                    steps {
                        dir('devopswiki-be/src') {
                            sh ''' 
                                python3 -m venv venv
                                . venv/bin/activate
                                pip install -r requirement.txt
                            '''
                        }
                    }
                }
                stage('React Frontend Build') {
                    steps {
                        dir('devopswiki-fe') {
                            sh 'npm ci && npm run build'
                        }
                    }
                }
            }
        }
        stage ('Test App') {
            steps {
                script {
                    echo 'No tests yet. Test stage will be worked on shortly'
                }
            }
        }
        stage ('SonarQube Analysis') {
            steps{
                withSonarQubeEnv('sonarqube'){
                    script {
                        def scannerHome = tool 'sonar-scanner'
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                                -Dsonar.projectKey=devopswiki \
                                -Dsonar.sources=devopswiki-fe/src,devopswiki-be/src \
                                -Dsonar.host.url=http://localhost:9000
                        """
                    }
                }
            }
            post {
                success {
                    script {
                        timeout(time: 2, unit: 'MINUTES') {
                            def qualityGate = waitForQualityGate()
                            if (qualityGate.status != 'OK') {
                                error "SonarQube Quality Gate failed: ${qualityGate.status}"
                            }else{
                                echo "SonarQube analysis passed."
                            }
                        }
                    }
                }
                failure {
                    echo "SonarQube analysis failed during execution."
                }
            }
        }
        stage('Build Docker') {
            parallel {
                stage('Build & Push Frontend') {
                    steps {
                        dir('devopswiki-fe') {
                            withCredentials([usernamePassword(
                                credentialsId: 'dockerhub-credentials',
                                usernameVariable: 'DOCKERHUB_USER',
                                passwordVariable: 'DOCKERHUB_PASS'
                            )]) {
                                sh '''
                                    echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
                                    docker build -t $DOCKERHUB_USER/devopswiki:fe-testbed-latest .
                                    docker push $DOCKERHUB_USER/devopswiki:fe-testbed-latest
                                '''
                            }
                        }
                    }
                }
                stage('Build & Push Backend') {
                    steps {
                        dir('devopswiki-be/src') {
                            withCredentials([usernamePassword(
                                credentialsId: 'dockerhub-credentials',
                                usernameVariable: 'DOCKERHUB_USER',
                                passwordVariable: 'DOCKERHUB_PASS'
                            )]) {
                                sh '''
                                    echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
                                    docker build -t $DOCKERHUB_USER/devopswiki:be-testbed-latest .
                                    docker push $DOCKERHUB_USER/devopswiki:be-testbed-latest
                                '''
                            }
                        }
                    }
                }
            }
        }
        stage('Deploy Container') {
            parallel {
                stage('Deploy Frontend') {
                    steps {
                        dir('devopswiki-containerisation/frontend'){
                            withCredentials([usernamePassword(
                                credentialsId: 'dockerhub-credentials',
                                usernameVariable: 'DOCKERHUB_USER',
                                passwordVariable: 'DOCKERHUB_PASS'
                            )]){
                                sh ''' 
                                    docker-compose down || true
                                    docker-compose pull
                                    docker-compose up -d
                                '''
                            }
                        }
                    }
                }
                stage('Deploy Backend'){
                    steps {
                        dir('devopswiki-containerisation/backend'){
                            sh ''' 
                                docker-compose down || true
                                docker-compose pull
                                docker-compose up -d
                            '''
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Build was successful'
        }
        failure {
            echo 'Build failed. Check logs'
        }
    }
}